assets = {
            'EURUSD': ['Forex', 'USD'], 
            'EURAUD': ['Forex', 'AUDUSD'], 
            'EURSEK': ['Forex', 'USDSEK'],
            'GBPJPY': ['Forex', 'USDJPY'], 
            'GBPCAD': ['Forex', 'USDCAD'],
            'GBPUSD': ['Forex', 'GBPUSD'],
            'USDCAD': ['Forex', 'USDCAD'], 
            'USDJPY': ['Forex', 'USDJPY'],
            'AUDJPY': ['Forex', 'USDJPY'],
            'AUDUSD': ['Forex', 'AUDUSD'],
            'CHFZAR': ['Forex', 'USDZAR'],
            'CHFCNH': ['Forex', 'USDCNH'],
            'CHFCZK': ['Forex', 'USDCZK'],
            'CHFHUF': ['Forex', 'USDHUF'],
            'CHFHUF': ['Forex', 'USDHUF'],
            'CHFNOK': ['Forex', 'USDNOK'],
            'CHFPLN': ['Forex', 'USDPLN'],
            'CHFTRY': ['Forex', 'USDTRY'],
            'EURCNH': ['Forex', 'USDCNH'], 
            'EURJPY': ['Forex', 'USDJPY'], 
            'EURGBP': ['Forex', 'GBPUSD'], 
            'EURAUD': ['Forex', 'AUDUSD'], 
            'EURCAD': ['Forex', 'USDCAD'],
            'USDCNH': ['Forex', 'USDCNH'], 
            'CNHJPY': ['Forex', 'USDJPY'], 
            'CADJPY': ['Forex', 'USDJPY'],
            'GBPCNH': ['Forex', 'USDCNH'], 
            'GBPAUD': ['Forex', 'AUDUSD'], 
            'AUDCNH': ['Forex', 'USDCNH'], 
            'CADCNH': ['Forex', 'USDCNH'],

            'IBUS500': ['CFD', 'USD'],
            'IBUST100': ['CFD', 'USD'],
            'IBGB100': ['CFD', 'GBPUSD'],
            'IBDE30': ['CFD', 'EURUSD'],
            'IBFR40': ['CFD', 'EURUSD'],
            'IBJP225': ['CFD', 'USDJPY'],
            'IBHK50': ['CFD', 'USDHKD'],
            'IBAU200': ['CFD', 'AUDUSD'], 
            # 'XAUUSD': ['CMDTY', 'USD'],
            # 'IBM': ['STK', 'USD'],
            # 'GC': ['Future', 'USD']
        }